# Generated by Django 4.2.17 on 2024-12-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_reactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postreaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
